[package]
name = "c2rust-ast-exporter"
version = "0.13.0"
authors = [
        "The C2Rust Project Developers <c2rust@immunant.com>",
        "Eric Mertens <emertens@galois.com>",
        "Alec Theriault <atheriault@galois.com>",
]
links = "clangAstExporter"
license = "BSD-3-Clause"
homepage = "https://c2rust.com/"
repository = "https://github.com/immunant/c2rust"
description = "Clang AST extraction API for use in the C2Rust project"

[dependencies]
libc = "0.2"
serde = "1.0"
serde_bytes = "0.11"
serde_cbor = "0.9"

[build-dependencies]
bindgen = { version = "0.51", features = ["logging"] }
cmake = "0.1"
clang-sys = "0.28"
env_logger = "0.6"

[features]
default = []

# Force static linking of LLVM
llvm-static = []
