[package]
name = "c2rust-xcheck-backend-dynamic-dlsym"
description = "Cross-checking backend that uses dlsym to locate rb_xcheck"
version = "0.1.0"
authors = ["The C2Rust Project Developers <c2rust@immunant.com>"]
license = "BSD-3-Clause"
homepage = "https://c2rust.com/"
repository = "https://github.com/immunant/c2rust"

