[package]
name = "c2rust-analyze"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polonius-engine = "0.13.0"
rustc-hash = "1.1.0"
bitflags = "1.3.2"

[build-dependencies]
c2rust-build-paths = { path = "../c2rust-build-paths" }
print_bytes = "0.7"

[package.metadata.rust-analyzer]
rustc_private = true
