[workspace]
members = [
    "config",
    "config-capi",
    "derive-macros",
    "runtime",
    # TODO: rustc plugins are completely unsupported now,
    # so replace it with another approach or fold it
    # into the dynamic instrumentation wrapper. Keep the
    # old code around for reference until that happens.
    #"rustc-plugin",
    "backends/libclevrbuf-sys",
    "backends/libfakechecks-sys",
    "backends/dynamic-dlsym",
    "backends/zstd-logging",
]
default-members = [
    "config",
    "derive-macros",
    "runtime",
    #"rustc-plugin",
    "backends/dynamic-dlsym",
    "backends/zstd-logging",
]
exclude = [
    "tests",
    "rustc-plugin",
]
