[package]
name = "cross-check-config"
version = "0.1.0"
authors = ["Andrei Homescu <ah@immunant.com>"]

[features]
parse-syn = ["syn"]
parse-syntax = []
with-quote = []
scopes = []

[dependencies]
serde = { version = "1.0", features = ["rc"] }
serde_derive = "1.0"
serde_yaml = "0.7"
globset = "0.4.0"

syn = { version = "0.11.11", features = ["full", "visit"], optional = true }
