[package]
name = "c2rust-manual-preprocessors"
version = "0.1.0"
authors = ["The C2Rust Project Developers <c2rust@immunant.com>"]
edition = "2018"

[dependencies]
mdbook = "0.2.2"
clap = "2.32.0"
serde_json = "1.0.33"
regex = "1.1.0"
env_logger = "0.6.0"
log = "0.4.6"
lazy_static = "1.2.0"
pulldown-cmark = "0.2"
pulldown-cmark-to-cmark = "1.1.0"

[[bin]]
name = "mdbook-include_md"
path = "include_md.rs"
