[package]
name = "c2rust-xcheck-fakechecks-zstd"
version = "0.1.0"
authors = ["Andrei Homescu <ah@immunant.com>"]

[lib]
crate-type = ["lib", "cdylib"]

[[bin]]
name = "xcheck-printer"
path = "src/bin/printer.rs"

[dependencies]
lazy_static = "1.1.0"
zstd = "0.4"
