[package]
name = "related_decls"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_util = { path = "../rust_util" }

clap = { version = "4.5", features = ["derive"] }
log = "=0.4.28"

ra_ap_hir = "=0.0.301"
ra_ap_hir_def = "=0.0.301"
ra_ap_ide_db = "=0.0.301"
ra_ap_load-cargo = "=0.0.301"
ra_ap_project_model = "=0.0.301"
ra_ap_syntax = "=0.0.301"
env_logger = {version = "0.11.8", features = ["color", "auto-color"]}
serde_json = "1.0.149"
itertools = "0.14.0"
