[package]
name = "c2rust-xcheck-runtime"
description = "Runtime library for C2Rust cross-checking"
version = "0.1.0"
authors = ["The C2Rust Development Team <c2rust@immunant.com>"]
license = "BSD-3-Clause"
homepage = "https://c2rust.com/"
repository = "https://github.com/immunant/c2rust"
readme = "README.md"

[features]
xcheck-with-dlsym = []
xcheck-with-weak = []
djb2-ssse3 = ["simd"]
libc-hash = []
fixed-length-array-hash = []

[dependencies]
simd = { version = "0.2.0", optional = true }
