[package]
name = "c2rust-xcheck-backend-libclevrbuf-sys"
description = "Native bindings to the libclevrbuf library"
version = "0.9.0"
authors = ["The C2Rust Project Developers <c2rust@immunant.com>"]
license = "BSD-3-Clause"
homepage = "https://c2rust.com/"
repository = "https://github.com/immunant/c2rust"
links = "clevrbuf"
build = "build.rs"

[lib]
name = "libclevrbuf_sys"
path = "lib.rs"
