[package]
name = "c2rust-xcheck-libclevrbuf-sys"
version = "0.1.0"
authors = ["Andrei Homescu <ah@immunant.com>"]
description = "Native bindings to the libclevrbuf library"
links = "clevrbuf"
build = "build.rs"

[lib]
name = "libclevrbuf_sys"
path = "lib.rs"
