[package]
name = "rust_util"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0.108", features = ["full", "visit-mut", "visit"] }
proc-macro2 = { version = "1", features = ["span-locations"] }
quote = "1"
