[package]
name = "split_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
rust_util = { path = "../rust_util" }

syn = { version = "2.0.108", features = ["full", "visit"] }
proc-macro2 = { version = "1", features = ["span-locations"] }
quote = "1"
clap = { version = "4.5", features = ["derive"] }

serde_json = "1"
