[package]
name = "c2rust-xcheck-derive"
description = "Derive crate for #[derive(XCheckHash)] used by C2Rust cross-checking"
version = "0.9.0"
authors = ["The C2Rust Project Developers <c2rust@immunant.com>"]
license = "BSD-3-Clause"
homepage = "https://c2rust.com/"
repository = "https://github.com/immunant/c2rust"
readme = "README.md"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.11.11", features = ["full", "visit"] }
synstructure = "0.6.1"
quote = "0.3.15"

[dependencies.c2rust-xcheck-config]
path = "../config"
version = "0.9.0"
features = ["parse-syn", "with-quote"]

[dev-dependencies]
c2rust-xcheck-runtime = { path = "../runtime", version = "0.9.0" }
c2rust-bitfields = { path = "../../../c2rust-bitfields", version = "0.2" }
c2rust-bitfields-derive = { path = "../../../c2rust-bitfields-derive", version = "0.1" }
