[package]
name = "split_ffi_entry_points"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0.108", features = ["full"] }
proc-macro2 = { version = "1", features = ["span-locations"] }
