[package]
name = "c2rust-xcheck-backend-libfakechecks-sys"
description = "Native bindings to the fakechecks library"
version = "0.9.0"
authors = ["The C2Rust Project Developers <c2rust@immunant.com>"]
license = "BSD-3-Clause"
homepage = "https://c2rust.com/"
repository = "https://github.com/immunant/c2rust"
links = "fakechecks"
build = "build.rs"
publish = false

[lib]
name = "libfakechecks_sys"
path = "lib.rs"
