[package]
name = "c2rust-xcheck-backend-libfakechecks-sys"
version = "0.1.0"
authors = ["Andrei Homescu <ah@immunant.com>"]
description = "Native bindings to the fakechecks library"
links = "fakechecks"
build = "build.rs"

[lib]
name = "libfakechecks_sys"
path = "lib.rs"
