[package]
name = "c2rust-xcheck-config-capi"
description = "C API for the C2Rust cross-check configuration parser"
version = "0.1.0"
authors = ["The C2Rust Development Team <c2rust@immunant.com>"]
license = "BSD-3-Clause"
homepage = "https://c2rust.com/"
repository = "https://github.com/immunant/c2rust"

[lib]
crate-type = ["staticlib"]

[dependencies]
serde = { version = "1.0", features = ["rc"] }
serde_yaml = "0.7"
c2rust-xcheck-config = { path = "../config", features = ["scopes"] }
